spring:
  application:
     name: rest-with-spring-boot-and-java-erudio
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3333/rest_with_spring_boot_erudio?useTimeZone=true&serverTimeZone=UTC
     username: root
     password: 6817
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view:
logging:
  level:
  #  root: WARN
    br.com.erudio: DEBUG
